version: "3"

networks:
  uas:
    external: true

services:
  db-uas:
    image: mysql:8.0
    container_name: db-uas
    command: --sql_mode=""
    ports:
      - 3307:3306
    volumes:
      - ./initDb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 3GkB8VL0lJaKApDP
    networks:
      - uas
    labels:
      - traefik.enable=false
    restart: always
  auth-uas:
    image: auth
    hostname: auth
    container_name: auth-uas
    command: make start
    build:
      context: ../authentication
      dockerfile: Dockerfile
    ports:
      - 40021:40000
    volumes:
      - type: bind
        source: ../authentication
        target: /home/app
      - type: bind
        source: ../authentication/db/migrations
        target: /home/app/migrations
    working_dir: /home/app
    environment:
      JWT_PRIVATE: 6a935e6baca5757a3b77a2fe747a71b9466951e0b555448413547d656042ed9acf63526baaad8e75cf13821ecba4881ca42a4366d8f2e3a08d49fb567ea1da57
      JWT_PUBLIC: cf63526baaad8e75cf13821ecba4881ca42a4366d8f2e3a08d49fb567ea1da57
      JWT_REFRESH: wuVXMq19t7UssgA46yOyPnH8BpVEONcasPen4uV9BRhEHQeckP
      DB_NAME: auth
      DB_USER: auth
      DB_SECRET: 3GkB8VL0lJaKApDP
      DB_HOST: db-uas
    networks:
      - uas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Path(`/auth`) || PathPrefix(`/auth/`)"
      - "traefik.http.routers.auth.priority=200"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=5050"
    restart: always
  todo-uas:
    image: todo
    hostname: todo
    container_name: todo-uas
    command: make start
    build:
      context: ../todo
      dockerfile: Dockerfile
    ports:
      - 40022:40000
    volumes:
      - type: bind
        source: ../todo
        target: /home/app
      - type: bind
        source: ../todo/db/migrations
        target: /home/app/migrations
    working_dir: /home/app
    environment:
      DB_NAME: todo
      DB_USER: todo
      DB_SECRET: 3GkB8VL0lJaKApDP
      DB_HOST: db-uas
    networks:
      - uas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.rule=Path(`/todo`) || PathPrefix(`/todo/`)"
      - "traefik.http.routers.todo.priority=200"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.routers.todo.tls=true"
      - "traefik.http.routers.todo.tls.certresolver=myresolver"
      - "traefik.http.services.todo.loadbalancer.server.port=5050"
    restart: always
  user-uas:
    image: user
    hostname: user
    container_name: user-uas
    command: make start
    build:
      context: ../user
      dockerfile: Dockerfile
    ports:
      - 40023:40000
    volumes:
      - type: bind
        source: ../user
        target: /home/app
      - type: bind
        source: ../user/db/migrations
        target: /home/app/migrations
    working_dir: /home/app
    environment:
      DB_NAME: user
      DB_USER: user
      DB_SECRET: 3GkB8VL0lJaKApDP
      DB_HOST: db-uas
    networks:
      - uas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Path(`/user`) || PathPrefix(`/user/`)"
      - "traefik.http.routers.user.priority=200"
      - "traefik.http.routers.user.entrypoints=websecure"
      - "traefik.http.routers.user.tls=true"
      - "traefik.http.routers.user.tls.certresolver=myresolver"
      - "traefik.http.services.user.loadbalancer.server.port=5050"
    restart: always
